const jobs=[
{id:'chen-brandkemy-dme',title:'Digital Marketing Executive',company:'BrandKemy',city:'Chennai',location:'Chennai',experience:'1–3 years',category:'Digital Marketing',workMode:'Office',salary:'Check source',posted:'Verified today',skills:['Digital Strategy','Lead Generation','Social Media','Communication'],summary:'Drive digital campaigns, support sales and help convert business enquiries.',responsibilities:['Plan and execute digital campaigns','Support lead generation and follow-up','Coordinate social content and reporting'],questions:['How would you generate leads for a service business?','Which campaign metrics would you report weekly?','Describe a campaign you would improve and why.'],source:'https://in.linkedin.com/jobs/digital-marketing-jobs-chennai'},
{id:'chen-one-mg-analyst',title:'Digital Marketing Analyst',company:'One MG',city:'Chennai',location:'Chennai',experience:'1–3 years',category:'Digital Marketing',workMode:'Hybrid',salary:'Check source',posted:'Verified today',skills:['Analytics','Advertising','Reporting','Excel'],summary:'Analyse digital advertising performance and turn campaign data into recommendations.',responsibilities:['Monitor performance dashboards','Explain campaign movements','Recommend optimisation tests'],questions:['Explain CTR, CPC, CPL and ROAS.','How do you investigate a sudden conversion drop?','What makes a useful client report?'],source:'https://in.linkedin.com/jobs/digital-marketing-jobs-chennai'},
{id:'chen-capminds-content',title:'Content Writer — SEO',company:'CapMinds',city:'Chennai',location:'Chennai',experience:'Fresher',category:'Content',workMode:'Office',salary:'₹15K–₹20K',posted:'Verified today',skills:['Content Writing','SEO','Research','Editing'],summary:'Create search-friendly content for websites, blogs and digital campaigns.',responsibilities:['Research assigned topics','Write SEO-focused articles','Edit content for clarity and originality'],questions:['How do you identify search intent?','Show two writing samples.','How do you place keywords naturally?'],source:'https://in.indeed.com/q-seo-content-writer-l-chennai%2C-tamil-nadu-jobs.html'},
{id:'chen-q-square-social',title:'Social Media Marketing Executive',company:'Q Square Ads',city:'Chennai',location:'T. Nagar',experience:'Fresher',category:'Social Media',workMode:'Office',salary:'₹15K–₹30K',posted:'Verified 1 day ago',skills:['Instagram','Meta Ads','Content Calendar','Canva'],summary:'Create and manage social campaigns for local brands and growing businesses.',responsibilities:['Build monthly content calendars','Coordinate creatives and publishing','Track engagement and campaign results'],questions:['Create a seven-day content plan.','How would you improve low engagement?','What would you include in a monthly report?'],source:'https://apna.co/jobs/social_media_marketing-jobs-in-chennai'},
{id:'chen-seo-executive',title:'SEO Executive',company:'Smarther',city:'Chennai',location:'Chennai',experience:'1–3 years',category:'SEO',workMode:'Office',salary:'Check source',posted:'Verified 2 days ago',skills:['Keyword Research','On-page SEO','Search Console','Technical SEO'],summary:'Improve rankings and organic traffic through research, optimisation and reporting.',responsibilities:['Perform keyword research','Optimise pages and content','Monitor indexing and organic performance'],questions:['How do you audit a new website?','Explain canonical tags and indexing.','Which Search Console reports do you use?'],source:'https://in.indeed.com/q-seo-executive-l-chennai%2C-tamil-nadu-jobs.html'},
{id:'chen-artistic-dme',title:'Digital Marketing Executive',company:'Artistic Artforum',city:'Chennai',location:'Ashok Nagar',experience:'Fresher',category:'Digital Marketing',workMode:'Office',salary:'₹18K–₹20K',posted:'Verified 2 days ago',skills:['Content','Canva','Social Media','Campaigns'],summary:'Entry-level role supporting creative campaigns and digital publishing.',responsibilities:['Create basic campaign assets','Publish social content','Support marketing coordination'],questions:['Show a sample post or reel.','How would you promote an art workshop?','Which metrics show content quality?'],source:'https://apna.co/jobs/digital_marketing_executive-jobs-in-chennai'},
{id:'pondy-big7-seo',title:'SEO Analyst',company:'Big7Solutions And Media',city:'Pondicherry',location:'Pondicherry',experience:'1–3 years',category:'SEO',workMode:'Office',salary:'From ₹20K',posted:'Verified today',skills:['SEO','Analytics','HTML','Search Console'],summary:'Own technical SEO, keyword research and organic search improvement.',responsibilities:['Run technical SEO audits','Build keyword plans','Report rankings and search performance'],questions:['Walk through a technical audit.','How do you prioritise keyword opportunities?','How do you diagnose an indexing problem?'],source:'https://www.simplyhired.co.in/search?l=puducherry%2C+puducherry&q=digital+marketing'},
{id:'pondy-cleodiva-marketer',title:'Digital Marketer',company:'Cleodiva',city:'Pondicherry',location:'Pondicherry',experience:'Fresher',category:'Social Media',workMode:'Office',salary:'₹10K–₹12K',posted:'Verified today',skills:['Instagram','Canva','CapCut','Meta Ads'],summary:'Plan Instagram reels, posts and stories with basic advertising support.',responsibilities:['Plan weekly social content','Create simple reels and graphics','Support Meta campaigns'],questions:['Show your best reel.','Create a one-week content plan.','How would you target a local audience?'],source:'https://in.indeed.com/q-digital-marketing-l-puducherry-jobs.html'},
{id:'pondy-valvenet-ai',title:'AI Digital Content Creator',company:'Valvenet Technologies',city:'Pondicherry',location:'Pondicherry',experience:'Fresher',category:'Creative',workMode:'Office',salary:'Check source',posted:'Verified 1 day ago',skills:['AI Content','Video','Prompting','Social Media'],summary:'Create AI-assisted images, videos and social content for digital campaigns.',responsibilities:['Generate campaign concepts','Create and refine AI visuals','Maintain brand consistency'],questions:['Show AI content samples.','How do you verify generated content?','Explain your prompt and revision workflow.'],source:'https://in.indeed.com/q-digital-marketing-l-puducherry-jobs.html'},
{id:'pondy-trinite-video',title:'Creative Video Editor',company:'Trinite Digital',city:'Pondicherry',location:'Pondicherry',experience:'1–3 years',category:'Creative',workMode:'Office',salary:'₹10K–₹20K',posted:'Verified 2 days ago',skills:['Video Editing','Reels','Storytelling','Captions'],summary:'Create short-form promotional videos for social platforms and campaigns.',responsibilities:['Edit reels and promotional videos','Add captions and sound','Handle creative revisions'],questions:['Show a short showreel.','How do you create a strong first-second hook?','How do you handle revision feedback?'],source:'https://www.simplyhired.co.in/search?l=puducherry%2C+puducherry&q=digital+marketing'},
{id:'pondy-sadhisha-manager',title:'Real Estate Marketing Manager',company:'Sadhisha Homes',city:'Pondicherry',location:'Pondicherry',experience:'3+ years',category:'Digital Marketing',workMode:'Office',salary:'₹20K–₹25K',posted:'Verified 3 days ago',skills:['Lead Generation','Campaigns','Project Management','CRM'],summary:'Plan property campaigns and build a consistent qualified-lead pipeline.',responsibilities:['Own monthly campaign planning','Coordinate lead follow-up','Track channel and project performance'],questions:['Design a property lead funnel.','How would you allocate a monthly budget?','How do you measure lead quality?'],source:'https://www.simplyhired.co.in/search?l=puducherry%2C+puducherry&q=digital+marketing'},
{id:'pondy-aakhaash-intern',title:'Digital Marketing Intern',company:'Aakhaash Institute of Media Studies',city:'Pondicherry',location:'Pondicherry',experience:'Fresher',category:'Digital Marketing',workMode:'Office',salary:'₹1K–₹5K',posted:'Verified 3 days ago',skills:['Social Media','Content','Canva','Digital Basics'],summary:'Gain practical exposure through live content and marketing projects.',responsibilities:['Assist content creation','Support campaign execution','Learn reporting fundamentals'],questions:['What is digital marketing?','Show one personal or college project.','How would you plan a week of content?'],source:'https://www.simplyhired.co.in/search?l=puducherry%2C+puducherry&q=digital+marketing'}
];

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={query:'',city:'all',experience:'all',category:'all',currentJob:null,tracker:JSON.parse(localStorage.getItem('marketready_tracker')||'{}')};
const stages=['saved','applied','interview','offer'];

function saveState(){localStorage.setItem('marketready_tracker',JSON.stringify(state.tracker));updateCounts()}
function updateCounts(){const count=Object.keys(state.tracker).length;$('#trackerCount').textContent=count}
function filteredJobs(){return jobs.filter(j=>{const hay=`${j.title} ${j.company} ${j.skills.join(' ')}`.toLowerCase();return(!state.query||hay.includes(state.query))&&(state.city==='all'||j.city===state.city)&&(state.experience==='all'||j.experience===state.experience)&&(state.category==='all'||j.category===state.category)})}
function renderJobs(){const list=filteredJobs();$('#visibleCount').textContent=list.length;$('#emptyState').hidden=!!list.length;$('#jobGrid').innerHTML=list.map(job=>`<article class="job-card"><div class="job-top"><span>${job.posted}</span><span class="verified">● VERIFIED</span></div><h2>${job.title}</h2><div class="company">${job.company}</div><div class="meta"><span>${job.city}</span><span>${job.experience}</span><span>${job.workMode}</span><span>${job.salary}</span></div><div class="skills">${job.skills.slice(0,4).map(s=>`<span class="skill">${s}</span>`).join('')}</div><div class="job-actions"><button class="primary-btn" onclick="openJob('${job.id}')">View role & prepare</button><button class="icon-btn ${state.tracker[job.id]?'saved':''}" onclick="toggleSave('${job.id}')" aria-label="Save ${job.title}">${state.tracker[job.id]?'★':'☆'}</button></div></article>`).join('')}
function toggleSave(id){if(state.tracker[id])delete state.tracker[id];else state.tracker[id]='saved';saveState();renderJobs()}
function openJob(id){const job=jobs.find(j=>j.id===id);state.currentJob=job;const saved=state.tracker[id];$('#jobDetail').innerHTML=`<div class="detail-head"><button class="dialog-close" onclick="jobDialog.close()" aria-label="Close">×</button><p class="eyebrow">${job.category.toUpperCase()} · ${job.city.toUpperCase()}</p><h2>${job.title}</h2><h3>${job.company} · ${job.location} · ${job.salary}</h3></div><div class="detail-body"><section class="detail-section"><h3>ROLE OVERVIEW</h3><p>${job.summary}</p><div class="skills">${job.skills.map(s=>`<span class="skill">${s}</span>`).join('')}</div></section><section class="detail-section"><h3>WHY PREPARE</h3><p>You need ${job.skills.length} core skills for this role. Take the readiness check to see where you are strong and what to revise.</p><button class="primary-btn accent-btn" onclick="startQuiz('${job.id}')">Check my readiness</button></section><section class="detail-section"><h3>WHAT YOU WOULD DO</h3><ul>${job.responsibilities.map(x=>`<li>${x}</li>`).join('')}</ul></section><section class="detail-section"><h3>LIKELY INTERVIEW QUESTIONS</h3><ol>${job.questions.map(x=>`<li>${x}</li>`).join('')}</ol></section></div><div class="detail-cta"><a class="primary-btn" href="${job.source}" target="_blank" rel="noopener" onclick="markApplied('${job.id}')">View source / apply</a><button class="primary-btn ${saved?'accent-btn':''}" onclick="toggleTrackFromDetail('${job.id}')">${saved?'Saved to tracker':'Save this job'}</button><a class="primary-btn accent-btn" href="https://wa.me/917397559527?text=${encodeURIComponent(`Hi Prakash, I want a mock interview for the ${job.title} role at ${job.company}.`)}" target="_blank" rel="noopener">WhatsApp mock interview</a></div>`;$('#jobDialog').showModal();history.replaceState(null,'',`#job/${job.id}`)}
function toggleTrackFromDetail(id){toggleSave(id);openJob(id)}
function markApplied(id){state.tracker[id]='applied';saveState()}

function startQuiz(id){const job=jobs.find(j=>j.id===id);state.currentJob=job;$('#quizRole').textContent=`${job.title} at ${job.company}`;$('#quizQuestions').innerHTML=job.skills.map((skill,i)=>`<div class="quiz-question"><p>${i+1}. How confident are you with ${skill}?</p><div class="quiz-options">${[['0','Need to learn'],['1','Basic'],['2','Confident']].map(([v,l])=>`<label><input required type="radio" name="q${i}" value="${v}"><span>${l}</span></label>`).join('')}</div></div>`).join('');$('#quizResult').hidden=true;$('#quizForm').hidden=false;$('#jobDialog').close();$('#quizDialog').showModal()}
$('#quizForm').addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(e.currentTarget);let points=0;state.currentJob.skills.forEach((_,i)=>points+=Number(fd.get(`q${i}`)||0));const score=Math.round(points/(state.currentJob.skills.length*2)*100);const message=score>=75?'Strong match. Prepare examples and practise your delivery.':score>=50?'Promising match. Strengthen the missing skills before the interview.':'Early-stage match. Build the fundamentals and practise before applying.';$('#quizForm').hidden=true;$('#quizResult').hidden=false;$('#quizResult').innerHTML=`<button class="dialog-close" onclick="quizDialog.close()" aria-label="Close">×</button><div class="score-ring" style="--score:${score*3.6}deg"><strong>${score}%</strong></div><div class="result-copy"><p class="eyebrow">YOUR READINESS RESULT</p><h2>${message}</h2><p>Your score is based on self-assessment across ${state.currentJob.skills.join(', ')}.</p></div><div class="result-actions"><button class="primary-btn" onclick="quizDialog.close();openJob('${state.currentJob.id}')">Back to role</button><a class="primary-btn accent-btn" href="https://wa.me/917397559527?text=${encodeURIComponent(`Hi Prakash, my readiness score for ${state.currentJob.title} at ${state.currentJob.company} is ${score}%. I want help preparing.`)}" target="_blank" rel="noopener">Improve with Prakash</a></div>`});

function setView(view){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`${view}View`));$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='tracker')renderTracker();location.hash=view}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));
function renderTracker(){const labels={saved:'Saved',applied:'Applied',interview:'Interview',offer:'Offer'};$('#trackerBoard').innerHTML=stages.map((stage,stageIndex)=>{const items=Object.entries(state.tracker).filter(([,s])=>s===stage).map(([id])=>jobs.find(j=>j.id===id)).filter(Boolean);return`<section class="tracker-column"><h2>${labels[stage]} <span>${items.length}</span></h2>${items.map(j=>`<article class="tracker-item"><h3>${j.title}</h3><p>${j.company}<br>${j.city}</p><div class="tracker-controls">${stageIndex>0?`<button onclick="moveJob('${j.id}',-1)">Back</button>`:''}<button onclick="openJob('${j.id}')">View</button>${stageIndex<stages.length-1?`<button onclick="moveJob('${j.id}',1)">Next</button>`:''}</div></article>`).join('')||'<p class="empty-column">No jobs yet</p>'}</section>`}).join('')}
function moveJob(id,delta){const i=stages.indexOf(state.tracker[id]);state.tracker[id]=stages[Math.max(0,Math.min(stages.length-1,i+delta))];saveState();renderTracker()}

$('#searchInput').addEventListener('input',e=>{state.query=e.target.value.trim().toLowerCase();renderJobs()});$('#cityFilter').addEventListener('change',e=>{state.city=e.target.value;renderJobs()});$('#experienceFilter').addEventListener('change',e=>{state.experience=e.target.value;renderJobs()});$('#roleFilter').addEventListener('change',e=>{state.category=e.target.value;renderJobs()});$('#clearFilters').addEventListener('click',()=>{state.query='';state.city=state.experience=state.category='all';$('#searchInput').value='';$('#cityFilter').value=$('#experienceFilter').value=$('#roleFilter').value='all';renderJobs()});$('#resetTracker').addEventListener('click',()=>{if(confirm('Clear all saved and tracked jobs on this device?')){state.tracker={};saveState();renderTracker();renderJobs()}});
$('#jobDialog').addEventListener('close',()=>{if(location.hash.startsWith('#job/'))history.replaceState(null,'','#jobs')});
renderJobs();updateCounts();const initialHash=location.hash.slice(1);if(initialHash==='tracker')setView('tracker');else if(initialHash.startsWith('job/')){const id=initialHash.split('/')[1];if(jobs.some(j=>j.id===id))openJob(id)}
